# Generated by Django 4.1.2 on 2022-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название проэкта')),
                ('slug', models.SlugField(max_length=200, verbose_name='Уникальный url')),
                ('opis', models.CharField(db_index=True, max_length=200, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='static/img/site', verbose_name='Обложка')),
                ('available', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('utl_git', models.CharField(db_index=True, max_length=200, verbose_name='Url гитхаба')),
            ],
        ),
    ]
